apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-helm
  namespace: demo-helm
spec:
  selector:
    matchLabels:
      app: demo-helm
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-helm
    spec:
      containers:
        - name: demo-helm
          image: demo-helm:1.0-SNAPSHOT
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /ping
              port: 8080
          readinessProbe:
            httpGet:
              path: /ping
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
