apiVersion: v1
kind: Service
metadata:
  name: demo-helm
  namespace: demo-helm
spec:
  type: NodePort
  selector:
    app: demo-helm
  ports:
    - protocol: TCP
      port: 8080
#      targetPort: 8080
      nodePort: 30303
